[logger]
type = "production"
dest = ".lntop/lntop.log"

[network]
name = "lnd"
type = "lnd"
address = "//127.0.0.1:10009"
cert = "/var/lnd/.lnd/tls.cert"
macaroon = "/var/lnd/macaroon/readonly.macaroon"
macaroon_timeout = 60
max_msg_recv_size = 52428800
conn_timeout = 1000000
pool_capacity = 4

[network.aliases]
# Not all peers have aliases set up. In order to remember who is whom, pubkeys can be annotated.
# "Forced" aliases will be printed in a different color to be distinguished from network advertised aliases.

[views]
# views.channels is the view displaying channel list.

[views.channels]
# It is possible to add, remove and order columns of the
# table with the array columns. The available values are:
columns = [
  "STATUS",      # status of the channel
  "ALIAS",       # alias of the channel node
  "GAUGE",       # ascii bar with percent local/capacity
  "LOCAL",       # the local amount of the channel
  "REMOTE",      # the remote amount of the channel
  "BASE_OUT",    # the outgoing base fee of the channel
  "RATE_OUT",    # the outgoing fee rate in ppm of the channel
  "BASE_IN",     # the incoming base fee of the channel
  "RATE_IN",     # the incoming fee rate in ppm of the channel
  "CAP",         # the total capacity of the channel
  "SENT",        # the total amount sent
  "RECEIVED",    # the total amount received
  "HTLC",        # the number of pending HTLC
  "UNSETTLED",   # the amount unsettled in the channel
  "CFEE",        # the commit fee
  "LAST UPDATE", # last update of the channel
  "AGE",         # approximate channel age
  "PRIVATE",     # true if channel is private
  "ID",          # the id of the channel
  "SCID",        # short channel id (BxTxO formatted)
  "NUPD",        # number of channel updates
]

[views.channels.options]
# Currently only one option for the AGE column. If enabled, uses multiple colors
# from green to orange to indicate the channel age using 256 color scheme in
# supported terminals

AGE = { color = "color" }

[views.transactions]
# It is possible to add, remove and order columns of the
# table with the array columns. The available values are:
columns = [
  "DATE",      # date of the transaction
  "HEIGHT",    # block height of the transaction
  "CONFIR",    # number of confirmations
  "AMOUNT",    # amount moved by the transaction
  "FEE",       # fee of the transaction
  "ADDRESSES", # number of transaction output addresses
]

[views.routing]
columns = [
  "DIR",            # event type:  send, receive, forward
  "STATUS",         # one of: active, settled, failed, linkfail
  "IN_CHANNEL",     # channel id of the incomming channel
  "IN_ALIAS",       # incoming channel node alias
  "IN_SCID",        # incoming short channel id (BxTxO)
  "IN_HTLC",        # htlc id on incoming channel
  "IN_TIMELOCK",    # incoming timelock height
  "OUT_CHANNEL",    # channel id of the outgoing channel
  "OUT_ALIAS",      # outgoing channel node alias
  "OUT_SCID",       # outgoing short channel id (BxTxO)
  "OUT_HTLC",       # htlc id on outgoing channel
  "OUT_TIMELOCK",   # outgoing timelock height
  "AMOUNT",         # routed amount
  "FEE",            # routing fee
  "LAST UPDATE",    # last update
  "DETAIL",         # error description
]

[views.fwdinghist]
columns = [
  "ALIAS_IN",	    # peer alias name of the incoming peer
  "ALIAS_OUT",      # peer alias name of the outgoing peer
  "AMT_IN",	    # amount of sats received
  "AMT_OUT",        # amount of sats forwarded
  "FEE",      	    # earned fee
  "TIMESTAMP_NS",   # forwarding event timestamp
  "CHAN_ID_IN",     # channel id of the incomming channel
  "CHAN_ID_OUT",    # channel id of the outgoing channel
]

[views.fwdinghist.options]
START_TIME = { start_time = "-6h" }
MAX_NUM_EVENTS = { max_num_events = "300" }
